[target.aarch64-linux-android]
# Force linker to align segments to 16 KiB pages (needed for new Android devices).
rustflags = [
    "-Clink-arg=-Wl,-z,common-page-size=16384",
    "-Clink-arg=-Wl,-z,max-page-size=16384",
]

[target.armv7-linux-androideabi]
rustflags = [
    "-Clink-arg=-Wl,-z,common-page-size=16384",
    "-Clink-arg=-Wl,-z,max-page-size=16384",
]

[target.x86_64-linux-android]
rustflags = [
    "-Clink-arg=-Wl,-z,common-page-size=16384",
    "-Clink-arg=-Wl,-z,max-page-size=16384",
]

[target.i686-linux-android]
rustflags = [
    "-Clink-arg=-Wl,-z,common-page-size=16384",
    "-Clink-arg=-Wl,-z,max-page-size=16384",
]
